### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by tobespc**
bump version to 3.1.0

### CODE REVIEW

**Comment by MichaelSitter** [comment]
Hey @tobespc! Just wondering if you have time to release this. Keen on using the hot-shots version.

**Comment by jeremy-j-ackso** [comment]
Any chance of a new release sometime soon? `appmetrics` recently updated, would be cool to have this use the new version along with `hot-shots`.

**Comment by v0vs** [comment]
Keenly waiting for a new version with `hot-shots` inside 🙏

**Review by mattcolegate — APPROVED** [review]
LGTM

**Pull request merged**
